<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Gyaneshs-MacBook-Pro.local" failures="1" tests="7" name="Safari Test" time="61.606" errors="0" timestamp="2025-09-10T19:08:18 IST">
  <testcase classname="test.LoginTest" name="urlTest" time="0.014"/>
  <testcase classname="test.LoginTest" name="titleTest" time="0.02"/>
  <testcase classname="test.LoginTest" name="loginTest" time="4.048"/>
  <testcase classname="test.DashBoardTest" name="verifyLogout" time="3.043">
    <skipped/>
  </testcase> <!-- verifyLogout -->
  <testcase classname="test.DashBoardTest" name="verifyLogout" time="2.988">
    <skipped/>
  </testcase> <!-- verifyLogout -->
  <testcase classname="test.DashBoardTest" name="verifyLogout" time="2.97">
    <skipped/>
  </testcase> <!-- verifyLogout -->
  <testcase classname="test.DashBoardTest" name="verifyLogout" time="2.99">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]
at test.DashBoardTest.verifyLogout(DashBoardTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogout -->
  <testcase classname="base.BasePage" name="@BeforeSuite beforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
</testsuite> <!-- Safari Test -->
